name: otax
title: OTS 2021
version: "19.07"
summary: OpenTaxSolver 2021
description: |
  This is a snap of OpenTaxSolver rev 2021.
  More info at https://opensource.com/article/21/2/linux-tax-software


grade: stable

base: core20
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf


apps:
  otax:
    command: bin/desktop-launch $SNAP/bin/wrapper.sh
    plugs: 
      - x11
      - unity7
      - home
    environment: 
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: "1"


parts:
  ots-build:
    plugin: make
    source:
        - on armhf: https://sourceforge.net/projects/opentaxsolver/files/OTS_2021/v19.07_linux/OpenTaxSolver2021_19.07_linux32.tgz/download
        - on arm64: "https://downloads.sourceforge.net/project/opentaxsolver/OTS_2021/v19.07_linux/OpenTaxSolver2021_19.07_linux64.tgz?ts=gAAAAABibLZVBlsXSDYyVCj-wxAFoMY-6t6QDaOgCK4LanwD_tP12zIRpqQUqKRxLJCXIziKxxaR4yZfYxYmDi59-_Z2nzRWxw%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopentaxsolver%2Ffiles%2FOTS_2021%2Fv19.07_linux%2FOpenTaxSolver2021_19.07_linux64.tgz%2Fdownload"
        - on amd64: https://sourceforge.net/projects/opentaxsolver/files/OTS_2021/v19.07_linux/OpenTaxSolver2021_19.07_linux64.tgz/download
    source-type: tar

    override-build: |
        cd src
        sed -i 's_\.\./__g' Makefile
        mkdir bin
        make
        cp -r bin $SNAPCRAFT_PART_INSTALL/
        cp Run_taxsolve_GUI $SNAPCRAFT_PART_INSTALL/
        cp -r ../tax_form_files $SNAPCRAFT_PART_INSTALL/
        mkdir $SNAPCRAFT_PART_INSTALL/src
        cp -r formdata $SNAPCRAFT_PART_INSTALL/src/


  gui-build:
    plugin: make
    source: .
    override-pull: |
        cp -R $SNAPCRAFT_PART_SRC/../../ots-build/src/* $SNAPCRAFT_PART_SRC/
    override-build: |
        cd src/Gui_gtk
        sed -i 's_\.\./__g' makefile
        mkdir bin
        make
        cp -r bin $SNAPCRAFT_PART_INSTALL/

    build-packages:
        - libgtk2.0-dev
    after:
        - ots-build


  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - build-essential
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
        #missing      - ttf-ubuntu-font-family
        #?      - dmz-cursor-theme
        #?      - light-themes
        #already      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
        #missing      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5


  wrapper:
    plugin: dump
    source: snap/local
    organize:
      'wrapper.sh': 'bin/wrapper.sh'
      'default-script': 'example-script'
    after: [ots-build]

